### PR TITLE
Set LU matrices to zero when jacobian is a zero element

### LINKED ISSUE #625: Some data in the State variable may be corrupt
As identified by this issue https://github.com/NCAR/MUSICA-Performance-Comparison/issues/62, if we reuse the `State` variable between different iterations of `solve` function, the results are corrupt and we get `fail to converge` error message later.

Kyle commented that this was also the reason why he had to initialize the LU matrix to zero originally (https://github.com/NCAR/micm/issues/587).

This issue indicates that the LU matrix in `State` variable is not overwritten correctly between iterations (or we should not expect it to be overwritten correctly at all?).

### PR DESCRIPTION
**Pull request by K20shores**
Better version of #663

Closes #625 

See the issue for more detail, but this fixes a bug where the L or U matrix would sometimes not be set to the value in the jacobian matrix, leading to a drifting value of the LU matrices. This would lead to incorrect results and eventually the solver would stop converging. We noticed this in the performance repository and learned that we couldn't reuse the state matrix.

We started setting the LU matrices to zero back in #410, but later removed in #594 when we thought it was just an issue around a vectorized normalized error function. It wasn't.

### CODE REVIEW

File: test/unit/solver/test_linear_solver_policy.hpp [hunk 1]
```diff
@@ -204,6 +204,64 @@ void testRandomMatrix(std::size_t number_of_blocks)
       A, b, x, [&](const FloatingPointType a, const FloatingPointType b) -> void { EXPECT_NEAR(a, b, 1.0e-5); });
```
Comment (sjsprecious) [inline test/unit/solver/test_linear_solver_policy.hpp:204]: can we use a smaller tolerance here now?

File: test/unit/solver/test_linear_solver_policy.hpp
Comment (sjsprecious) [inline test/unit/solver/test_linear_solver_policy.hpp:1]: Also can we initialize the LU matrix with 0 rather than 1.e-30 now?

**Review by sjsprecious — COMMENTED** [review]
@K20shores Thanks for fixing this bug. It will make me sleep much better for the weekend.

Just a few minor comments but otherwise the PR looks good to me. Great job!

File: src/solver/lu_decomposition.cu [hunk 2]
```diff
@@ -62,6 +62,10 @@ namespace micm
               size_t A_idx = d_aik[aik_offset++] + tid;
               d_U[U_idx] = d_A[A_idx];
             }
+            else {
+              size_t U_idx = d_uik_nkj[uik_nkj_offset].first + tid;
```
Comment (boulderdaze) [inline src/solver/lu_decomposition.cu:66]: `Line 61` has the same definition. Maybe we could define it outside if conditional?

Comment (K20shores) [reply src/solver/lu_decomposition.cu:66]: I was noticing that too. There's a lot of redefinition in these and I was wondering if now would be a good time to remove those

Comment (boulderdaze) [reply src/solver/lu_decomposition.cu:66]: Yeah I think we can address them in this PR.

**Review by boulderdaze — CHANGES_REQUESTED** [review]
Looks good! I only have a minor change request. I think the test this PR brings in are very valuable.

File: test/unit/solver/test_linear_solver_policy.hpp
Comment (K20shores) [reply test/unit/solver/test_linear_solver_policy.hpp:1]: yes

File: include/micm/util/vector_matrix.hpp [hunk 3]
```diff
@@ -228,6 +228,17 @@ namespace micm
...
+      for (std::size_t i = 0; i < x_dim_; ++i)
+      {
+        for (std::size_t j = 0; j < y_dim_; ++j)
+        {
+          std::cout << (*this)[i][j] << " ";
+        }
+        std::cout << std::endl;
+      }
+    }
+
```
Comment (boulderdaze) [inline include/micm/util/vector_matrix.hpp:241]: Doesn't look like it is used anywhere, could you confirm it? Since we don't execute clang tidy automatically, could you name the function in CamelCase?

**Review by sjsprecious — APPROVED** [review]

File: src/solver/lu_decomposition.cu [hunk 4]
```diff
@@ -85,6 +87,11 @@ namespace micm
               size_t A_idx = d_aki[aki_offset++] + tid;
               d_L[L_idx] = d_A[A_idx];
             }
+            else {
+              size_t L_idx = d_lki_nkj[lki_nkj_offset].first + tid;
+              d_L[L_idx] = 0;
```
Comment (boulderdaze) [inline src/solver/lu_decomposition.cu:92]: The same line is found in `line 86`. I think we can define it outside the conditional

File: src/solver/lu_decomposition.cu [hunk 5]
```diff
@@ -85,6 +87,11 @@ namespace micm
...
+            }
+
             for (size_t ikj = 0; ikj < d_lki_nkj[lki_nkj_offset].second; ++ikj)
             {
               size_t L_idx_1 = d_lki_nkj[lki_nkj_offset].first + tid;
```
Comment (boulderdaze) [inline src/solver/lu_decomposition.cu:97]: I think this line can be deleted as well

File: include/micm/util/vector_matrix.hpp (hunk 3 above)
Comment (K20shores) [reply include/micm/util/vector_matrix.hpp:241]: It was useful when I was debugging. I'd like to keep it

File: src/solver/lu_decomposition.cu (hunk 5 above)
Comment (K20shores) [reply src/solver/lu_decomposition.cu:96]: fixed

Comment (boulderdaze) [reply src/solver/lu_decomposition.cu:96]: oh I was suggesting for line `94-101`
```C++
  for (size_t ikj = 0; ikj < d_lki_nkj[lki_nkj_offset].second; ++ikj)
  {
    size_t L_idx_1 = d_lki_nkj[lki_nkj_offset].first + tid;   // Delete this 
    ...
    d_L[L_idx] -= d_L[L_idx_2] * d_U[U_idx];    // Update d_L[L_idx_1] to d_L[L_idx] 
    ++lkj_uji_offset;
  }
```

File: include/micm/util/vector_matrix.hpp (hunk 3 above)
Comment (boulderdaze) [reply include/micm/util/vector_matrix.hpp:241]: Yeah that's fine with me. Would you be able to make it in CamelCase though for the consistency in our code base?

**Review by boulderdaze — APPROVED** [review]
Thank you for addressing the comments
